source 'https://rubygems.org'

gem 'openstax_aws', git: 'https://github.com/openstax/aws-ruby.git', ref: 'e9c48ed2b9aa4ca10823732a76646ed7c2fd6d99'
gem 'slop'
gem 'byebug'
gem 'rspec'
gem 'vcr'
gem 'webmock'
gem 'dotenv'
gem 'activesupport'
gem 'chronic'
gem 'thor'
gem 'rainbow'
gem 'command_line_reporter'
